name: Build-WF
on:
  push:
    branches:
      - 'feature*'
      - 'JIRA*'
run-name: "Build Job trigger by @${{ github.actor }} on the event : ${{ github.event_name }}"
      
jobs:
  Gradle-Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "Build complete."
  Docker-Build:
    runs-on: ubuntu-latest
    needs: Gradle-Build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
  Helm-Package:
    runs-on: ubuntu-latest
    needs: Docker-Build
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."