name: Build-Deploy-test
on:
   workflow_dispatch:
     inputs:
      Env:
        type: choice
        description: Environment to Deploy
        options: 
            - dev
            - test
            - bce
      branches:
        description: Branch to build
        required: true
jobs:
   Gradle-Build:
     runs-on: ubuntu-latest
     steps:
       - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
       - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub"
       - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
       - run: echo "Build complete."
   Docker-Build:
     runs-on: ubuntu-latest
     needs: Gradle-Build
     steps:
       - name: Check out repository code
         uses: actions/checkout@v3
       - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
       - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
   Helm-Package:
     runs-on: ubuntu-latest
     needs: Docker-Build
     steps:
       - name: List files in the repository
         run: |
           ls ${{ github.workspace }}
       - run: echo "ğŸ This job's status is ${{ job.status }}."
   Alert-to-Slack: 
     runs-on: ubuntu-latest
     needs: Helm-Package
     steps:
       - run: echo "Alert to slack....."


   Deploy-to-dev-env:
        runs-on: ubuntu-latest
        needs: Helm-Package
        if: ${{ github.event.inputs.Env == 'dev' }}
        steps: 
            - name: Deploy
              run: echo "Deploying in dev"

   Deploy-to-test-env:
        runs-on: ubuntu-latest
        needs: Helm-Package
        if: ${{ github.event.inputs.Env == 'test' }}
        steps: 
            - name: Deploy
              run: echo "Deploying in test"

   Deploy-to-bce-env:
        runs-on: ubuntu-latest
        needs: Helm-Package
        if: ${{ github.event.inputs.Env == 'bce' }}
        steps: 
            - name: Deploy
              run: echo "Deploying in bce"